       <?php
       $routes = [
       'getLobbyEventsByCode',
       'getTournamentCode',
       'getMockLobbyEventsByCode',
       'getBySummonerId',
       'getBySummonerName',
       'getByAccountId',
       'getVersions',
       'getSummonerSpellById',
       'getSummonerSpellList',
       'getRuneById',
       'getRuneList',
       'getRealm',
       'getProfileIcons',
       'getMasteryById',
       'getMasteryList',
       'getMapData',
       'getLanguages',
       'getLanguageStrings',
       'getItemById',
       'getItemList',
       'getChampionDataById',
       'getChampionList',
       'getFeaturedGames',
       'getCurrentGameInfoBySummoner',
       'getRunePagesBySummonerId',
       'getMatchTimeline',
       'getRecentMatchlist',
       'getMatchlist',
       'getMatchByTournamentCode',
       'getMatch',
       'getMatchIdsByTournamentCode',
       'getMasteryPagesBySummonerId',
       'getShardData',
       'getAllLeaguePositionsForSummoner',
       'getMasterLeague',
       'getAllLeaguesForSummoner',
       'getChallengerLeague',

       'getChampionById',
       'getChampions',
       'getChampionMasteryScore',
       'getSingleChampionMastery',
        'getAllChampionMasteries',
        'metadata'
       ];
       foreach ($routes as $file) {
           require __DIR__ . '/../src/routes/' . $file . '.php';
       }

